title:              Western Ukrainian Club
email:              your-email@example.com
description:        A Blog Theme by Start Bootstrap
author:             Lesqero
baseurl: /
url: http://westernukies.github.io


# Social Profiles
twitter_username:   SBootstrap
github_username:    StartBootstrap
facebook_username:  StartBootstrap
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

#admin rights
jekyll_admin:
  hidden_links:
#    - posts
#    - pages
    - staticfiles
    - datafiles
    - configuration
  homepage: "_pages"

  #ollections:
  #posts:
  #  output: true
  #  sidebar_label: News